### ISSUE TITLE
No conflict between mic and mic2 specified in spec and debian/control files

### ISSUE THREAD

**Issue by fvennetier** [jfding/mic#14]
An user of OBS Light reported that installing MIC and the old MIC2 on the same machine lead to problems (https://bugs.meego.com/show_bug.cgi?id=25013). We suggest adding adding _"Conflicts: mic2"_ in **mic.spec** and **debian/control** files.

**Comment by jfding** [comment]
Fixed in git tree, and updated the packages in meego.com OBS.
